export const START_LOAD_ITEMS = '@TODOS/START_LOAD_ITEMS';
export const ADD_ITEMS = '@TODOS/ADD_ITEMS';
export const LOAD_ITEMS_ERROR = '@TODOS/LOAD_ITEMS_ERROR';

export const START_PUSH_ITEM = '@TODOS/START_PUSH_ITEM';
export const ADD_ITEM = '@TODOS/ADD_ITEM';
export const PUSH_ITEM_ERROR = '@TODOS/PUSH_ITEM_ERROR';

export const START_DELETE_ITEM = '@TODOS/START_DELETE_ITEM';
export const DELETE_ITEM = '@TODOS/DELETE_ITEM';
export const DELETE_ITEM_ERROR = '@TODOS/DELETE_ITEM_ERROR';

export const START_UPDATE_ITEM = '@TODOS/START_UPDATE_ITEM';
export const UPDATE_ITEM = '@TODOS/UPDATE_ITEM';
export const UPDATE_ITEM_ERROR = '@TODOS/UPDATE_ITEM_ERROR';
